### ISSUE TITLE
"Exclusive" in output.conf is buggy

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-logstash#120]
There are two files that use that feature and both are buggy. It's in `simple-output.conf.j2` and `connector.conf.j2`.

Reproduce the error:
* Set pipeline to `exclusive: true`
* Define only a single output

Result: One extra `{` on top of the file that breaks the configurationl.

**Comment by martialblog** [comment]
Role will no longer be maintained. See https://github.com/NETWAYS/ansible-collection-elasticstack/
