### ISSUE TITLE
Tests show that putting roles into Elasticsearch has changed.

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-logstash#139]
As visible in https://github.com/NETWAYS/ansible-role-beats/runs/7151781062?check_suite_focus=true it looks like the proven way to put users and roles into Elasticsearch doesn't work anymore. We need to work around that.

**Comment by martialblog** [comment]
Role will no longer be maintained. See https://github.com/NETWAYS/ansible-collection-elasticstack/
