### ISSUE TITLE
Build workaround for broken /tmp directories

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-logstash#153]
On some systems Logsash can't use `/tmp` and need to switch to another directory. See https://discuss.elastic.co/t/logstast-startup-issue/41771/3 for details.

We have something similar in https://github.com/NETWAYS/ansible-role-elasticsearch/commit/2d8ad2a9d14ca46623d9745aeb2ded32d516912c

**Comment by martialblog** [comment]
Role will no longer be maintained. See https://github.com/NETWAYS/ansible-collection-elasticstack/
