### ISSUE TITLE
Activate security per default

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-logstash#34]
Other roles that work well with this one have security activated per default. The differing defaults give users a hard time.

Instead of just changing the default we need more to fix that:

* Add notes to readme about why and when you might want to disable security
* Check with Elastic 7.11 how to handle different versions. Up until now there's `logstash-oss` as package which lacks options like security. We need to make sure to reflect potential changes with the license change in 7.11 . It should be enough to open a new issue about keeping an eye on the changes. Nice would be a role that could work with different versions (not meaning version numbers, but regular, oss and maybe third party forks)

**Comment by widhalmt** [comment]
Thanks @dgoetz for reporting.

**Comment by widhalmt** [comment]
Enabling security by default has proven problematic. But I came up with another easy to use solution: https://github.com/NETWAYS/ansible-role-beats/pull/58/files#diff-3d0ff1709ca48add100327bb2a468e6c508fb92a159c64c4f99ad1df89d9bddeR3-R8

This will give us a set of 2 variables to set: `elastic_stack_full_stack` and `elastic_security`. The first means, that all our roles are used so they can work together. The second one means "enable security in the whole stack". If that's what you'd like to see @dgoetz and @Crited I'll start to change all our roles so we have a default of "security is off" but can enable it globally by just setting these two.

I know, "security is off" might sound like a bad idea but please consider that some users only use parts of the stack and enabling it by default would make automatic tests etc. harder. It doesn't mean, you can't use security it's more about "you can still use your own way of setting up security". What looks like a good idea to me, though:

* Have security off by default
* Have using the whole stack off by default
* When you enable using the whole stack using security is automatically on by default but can be overriden

**Comment by dgoetz** [comment]
Perfectly fine!
