### ISSUE TITLE
Allow for a mix of pipelines from different sources

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-logstash#35]
Right now we only allow fetching pipelines from git repos or completely manage pipelines manually. We should improve the `pipelines.yml` so that it also accepts a list of pipelines where the user has to manually place the pipeline.

A dictionary would work best. This way we could give names for pipelines and automatically create the directories to make typos impossible. But we just can't use a simple list because pipelines sometimes need more options like count of workers or type of queue.

Thanks to @dgoetz for showing that we need this feature.

**Comment by Nathaniel-Donahue** [comment]
A good first step to solve this issue could be changing "cert.p12" through "cert.*"

**Comment by dgoetz** [comment]
I think you mixed up the issues. ;-)
This one would be about having this task https://github.com/NETWAYS/ansible-role-logstash/blob/master/tasks/main.yml#L51 optional and alternative tasks for manual and perhaps file based configuration of pipelines.

**Comment by widhalmt** [comment]
You're right, @dgoetz 

And to not forget it: What we found out during our tests:
* We can not just add an empty directory as a pipeline. Logstash will try to start it as a pipeline and fail (at least to start that pipeline)
* Add a `.conf` file with only a comment doesn't work either. That's unusable config, too

So we can add the creation of custom pipelines but we need to add to the `README.md` that when someone uses this feature they need to make sure they provide configuration files. That also means we can't provide a default value to show how it works.

**Comment by martialblog** [comment]
Role will no longer be maintained. See https://github.com/NETWAYS/ansible-collection-elasticstack/
