### ISSUE TITLE
 Set defaults for all variables and mention them

### ISSUE THREAD

**Issue by Crited** [NETWAYS/ansible-role-logstash#4]
All variables should be mentioned, inside the `defaults/main.yml` even if not used and if possible or necessary have default values.

Like #3  `elastic_stack_full_stack` is necessary for the purpose of running the playbook at bare minimum configuration.

Others like `logstash_user` should be like: `logstash_system`
`logstash_password` could be left empty, but atleast be there as a comment.

**Comment by widhalmt** [comment]
@Crited could you check again? This should now be done if I didn't miss anything. I'd love to have your feedback, though.
