### ISSUE TITLE
Find a better place to put json files into

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-logstash#43]
Currently we place the files containing the `logstash_writer` role and use just into `root` on the Elasticsearch CA host. We should find a better place.

Hint: Maybe don't use a temporary directory so we don't need to change with every run.

**Comment by widhalmt** [comment]
Was closed by mistake.

**Comment by martialblog** [comment]
Role will no longer be maintained. See https://github.com/NETWAYS/ansible-collection-elasticstack/
