### ISSUE TITLE
Rethink Molecule scenarios

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-logstash#53]
We might have too many scenarios.

What we need:
* Check every supported OS
* Have a scenarios with as few variables set as possible
* Have a scenario with the rest of the stack (roles)
* Have every feature tested and activated at least once
* Maybe check some features if they work when deactivated, too
* Check X-Pack and OSS version

**Comment by martialblog** [comment]
Role will no longer be maintained. See https://github.com/NETWAYS/ansible-collection-elasticstack/
